In [12]:
import pandas as pd

import numpy as np

In [30]:
csv_path = "../OneDrive/desktop/BootCamp/Homework/zillowhomes.csv" 


zillow = pd.read_csv(csv_path,encoding="ISO-8859-1")

zillow

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
0,61639,10025,New York,NY,New York-Newark-Jersey City,New York County,1,168300.0,168400.0,168400.0,...,1115700,1108900,1097600,1086900,1080100,1072000,1065700,1051300,1027400,1009600
1,84654,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,160000.0,161000.0,161700.0,...,350100,348500,347300,347400,348800,350800,352800,353200,352700,353000
2,61637,10023,New York,NY,New York-Newark-Jersey City,New York County,3,353100.0,353700.0,354200.0,...,1501700,1487200,1461700,1439000,1412100,1391500,1381400,1373100,1364500,1361000
3,91982,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,210400.0,212200.0,212200.0,...,334400,335800,337100,338400,338500,337000,336100,335900,335100,334300
4,84616,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,5,194400.0,196100.0,197300.0,...,428200,428400,430000,430900,430000,430200,431700,432400,432200,432500
5,93144,79936,El Paso,TX,El Paso,El Paso County,6,77200.0,77200.0,77300.0,...,122200,123100,123600,124500,125700,126300,126800,127500,128200,128500
6,91940,77449,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,7,95400.0,95600.0,95800.0,...,176800,176900,177400,178100,178600,179500,180300,180900,182000,183000
7,91733,77084,Houston,TX,Houston-The Woodlands-Sugar Land,Harris County,8,94700.0,95000.0,95200.0,...,165400,166100,167000,168100,169100,170300,171800,173400,175400,177000
8,61616,10002,New York,NY,New York-Newark-Jersey City,New York County,9,NaN,NaN,NaN,...,996900,1001100,1002500,1002000,993100,979200,971200,963600,950600,943500
9,61807,10467,New York,NY,New York-Newark-Jersey City,Bronx County,10,140900.0,140900.0,140900.0,...,402200,407700,412100,415800,419300,421600,422000,422400,424100,426700
10,84640,60640,Chicago,IL,Chicago-Naperville-Elgin,Cook County,11,99400.0,101400.0,103300.0,...,242700,242000,240400,238600,237100,236500,236900,237300,237500,237800
11,62037,11226,New York,NY,New York-Newark-Jersey City,Kings County,12,153000.0,153000.0,152900.0,...,799600,815200,825200,829300,829300,829600,831500,831900,830400,829900
12,97564,94109,San Francisco,CA,San Francisco-Oakland-Hayward,San Francisco County,13,300300.0,300300.0,300300.0,...,1227300,1233200,1236600,1237500,1244300,1258100,1265000,1262400,1257500,1253700
13,61630,10016,New York,NY,New York-Newark-Jersey City,New York County,14,243700.0,242700.0,241600.0,...,1036800,1038200,1031700,1027700,1026900,1024400,1017900,1006400,993800,988100
14,74101,37013,Nashville,TN,Nashville-Davidson--Murfreesboro--Franklin,Davidson County,15,105500.0,106300.0,107100.0,...,206000,207400,209100,211000,213600,216500,218500,220000,221700,222900
15,92593,78660,Pflugerville,TX,Austin-Round Rock,Travis County,16,138800.0,138400.0,138300.0,...,243800,244700,245700,246400,246700,247400,248400,249200,249900,250400
16,71831,32162,The Villages,FL,The Villages,Sumter County,17,101400.0,101000.0,100600.0,...,253500,255500,257400,258900,260700,263000,264400,265200,266400,267300
17,62087,11375,New York,NY,New York-Newark-Jersey City,Queens County,18,229500.0,229500.0,230000.0,...,973900,972500,969800,965100,965000,972300,985100,994000,995700,997000
18,62045,11235,New York,NY,New York-Newark-Jersey City,Kings County,19,164100.0,164900.0,165900.0,...,724800,726200,724000,717800,713000,714200,716100,716000,714600,714100
19,84646,60647,Chicago,IL,Chicago-Naperville-Elgin,Cook County,20,136400.0,137400.0,138100.0,...,389100,389100,388000,387400,387100,390100,393700,394200,394000,395300
20,96107,90250,Hawthorne,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,21,151800.0,152100.0,152400.0,...,617800,621900,627000,632700,638800,645300,650900,654600,657500,658800
21,74242,37211,Nashville,TN,Nashville-Davidson--Murfreesboro--Franklin,Davidson County,22,92400.0,92800.0,93300.0,...,250700,251900,253000,254600,256700,259400,261500,262800,263900,264900
22,61643,10029,New York,NY,New York-Newark-Jersey City,New York County,23,188100.0,189800.0,191500.0,...,796000,790300,779400,774700,783200,793000,791900,784800,778800,776700
23,61623,10009,New York,NY,New York-Newark-Jersey City,New York County,24,NaN,NaN,NaN,...,1164700,1158800,1153000,1154500,1153300,1143700,1145500,1143600,1120300,1092400
24,84620,60618,Chicago,IL,Chicago-Naperville-Elgin,Cook County,25,138800.0,139500.0,140000.0,...,394200,392400,391300,391900,393300,394000,393600,393200,393200,393500
25,61625,10011,New York,NY,New York-Newark-Jersey City,New York County,26,343600.0,348200.0,352800.0,...,1731300,1708500,1680800,1670500,1670200,1666900,1661200,1654700,1642600,1633200
26,92036,77573,League City,TX,Houston-The Woodlands-Sugar Land,Galveston County,27,140100.0,139600.0,139200.0,...,262200,263600,264400,265600,267000,267600,267600,268100,269100,269900
27,92045,77584,Pearland,TX,Houston-The Woodlands-Sugar Land,Brazoria County,28,138500.0,138700.0,139200.0,...,259100,261200,262600,263000,263100,263700,264800,266200,267600,268400
28,61703,10128,New York,NY,New York-Newark-Jersey City,New York County,29,271900.0,270700.0,269600.0,...,1246200,1249000,1248200,1251400,1248600,1235700,1218600,1209200,1202400,1193300
29,66126,20002,Washington,DC,Washington-Arlington-Alexandria,District of Columbia,30,91500.0,91700.0,92000.0,...,640800,645900,651400,656300,662600,669900,675800,679200,678300,674900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15581,93425,80481,Ward,CO,Boulder,Boulder County,15582,126000.0,125300.0,124700.0,...,341400,345200,347900,351400,354700,356400,356500,357200,358700,359300
15582,66509,20618,Bushwood,MD,California-Lexington Park,Saint Marys County,15583,94600.0,95500.0,96400.0,...,200400,202700,201900,201200,201700,201500,200400,201600,203700,204800
15583,81745,54524,Fifield,WI,NaN,Price County,15584,81600.0,81600.0,81500.0,...,82900,82300,82800,83700,84700,86200,87300,87300,87500,88300
15584,66516,20625,Cobb Island,MD,Washington-Arlington-Alexandria,Charles County,15585,115600.0,114700.0,113600.0,...,219100,225100,228200,230600,232900,234100,234900,235200,235300,235800
15585,76680,43438,Kelleys Island,OH,Sandusky,Erie County,15586,NaN,NaN,NaN,...,222600,226400,232700,238000,241000,241600,241500,242500,244600,245300
15586,58327,1270,Windsor,MA,Pittsfield,Berkshire County,15587,105000.0,104200.0,103400.0,...,206400,208900,209900,210700,211400,211600,212000,212200,211400,210400
15587,70763,29915,Bluffton,SC,Hilton Head Island-Bluffton-Beaufort,Beaufort County,15588,312900.0,315700.0,318500.0,...,514100,521900,531100,522600,513600,514500,515200,513900,513500,510200
15588,93793,81430,Placerville,CO,NaN,San Miguel County,15589,239100.0,240900.0,242700.0,...,589000,600400,607900,614700,624300,629500,629000,628100,628500,626900
15589,94323,83821,Coolin,ID,Sandpoint,Bonner County,15590,NaN,NaN,NaN,...,526500,521100,518600,521100,533400,557500,584000,597700,608300,616700
15590,62599,12480,Shandaken,NY,Kingston,Ulster County,15591,68500.0,68300.0,68100.0,...,165100,164400,167100,172500,175800,176800,178300,178700,177700,177700
15591,59046,3215,Waterville Valley,NH,Claremont-Lebanon,Grafton County,15592,79600.0,79400.0,79200.0,...,183700,185300,186600,186400,185000,183800,184500,184700,185500,187200
15592,81944,54865,Port Wing,WI,NaN,Bayfield County,15593,NaN,NaN,NaN,...,70500,71100,71400,70300,70100,73400,76500,76600,77000,79000
15593,99401,97733,Crescent,OR,Klamath Falls,Klamath County,15594,NaN,NaN,NaN,...,244400,247200,248700,249500,249200,249000,249700,251600,251800,251100
15594,59210,3812,Bartlett,NH,NaN,Carroll County,15595,79100.0,79100.0,79100.0,...,196800,198500,199500,199800,200500,202100,204600,206200,206500,206500
15595,96805,92322,Crestline,CA,Riverside-San Bernardino-Ontario,San Bernardino County,15596,78600.0,78400.0,78200.0,...,202200,202700,203200,204600,206900,210100,213000,213900,213400,212900
15596,81916,54832,Drummond,WI,NaN,Bayfield County,15597,93600.0,93200.0,92800.0,...,113000,116100,118200,120700,122400,122300,122400,123700,124100,123200
15597,96822,92341,Green Valley Lake,CA,Riverside-San Bernardino-Ontario,San Bernardino County,15598,84100.0,84100.0,84200.0,...,187300,192400,196100,198500,200400,202300,204100,206300,208200,209300
15598,95893,89413,Glenbrook,NV,Gardnerville Ranchos,Douglas County,15599,562400.0,562800.0,562700.0,...,2064800,1991300,1932700,1911800,1936700,1992400,2078900,2167800,2225400,2251900
15599,62570,12444,Jewett,NY,NaN,Greene County,15600,102400.0,102600.0,102700.0,...,276800,277600,278800,280600,282200,284200,285800,286300,285600,284900
15600,59187,3765,Haverhill,NH,Claremont-Lebanon,Grafton County,15601,80700.0,80000.0,79300.0,...,127400,128600,130300,131100,131800,133100,134700,136200,137300,137600
15601,79338,48728,Curran,MI,NaN,Alcona County,15602,29900.0,30300.0,30700.0,...,74100,76400,77300,77500,78600,79100,79900,81200,81800,81000
15602,94711,84781,Pine Valley,UT,St. George,Washington County,15603,135900.0,136300.0,136600.0,...,268400,271800,276300,278600,280200,285900,293400,298400,301600,304400
15603,62556,12429,Esopus,NY,Kingston,Ulster County,15604,75800.0,75900.0,76100.0,...,180000,181500,182800,183400,183200,183200,184600,185700,186400,187500
15604,99032,97028,Rhododendron,OR,Portland-Vancouver-Hillsboro,Clackamas County,15605,137200.0,137400.0,137500.0,...,343800,343800,344000,343500,342600,343200,342300,339200,337200,338000
15605,62697,12720,Bethel,NY,NaN,Sullivan County,15606,61100.0,61300.0,61500.0,...,122900,125100,126400,126600,127300,129100,131900,134500,136400,137000
15606,99074,97102,Arch Cape,OR,Astoria,Clatsop County,15607,182600.0,183700.0,184800.0,...,596900,598800,602900,603100,607000,621300,634500,640000,639800,636100
15607,58333,1338,Buckland,MA,Greenfield Town,Franklin County,15608,90800.0,90800.0,90900.0,...,217800,219400,221000,221400,222500,225000,226200,226200,226600,226900
15608,59107,3293,Woodstock,NH,Claremont-Lebanon,Grafton County,15609,81600.0,81000.0,80400.0,...,172600,172300,172800,175000,176800,177900,178900,179600,180700,182300
15609,75672,40404,Berea,KY,Richmond-Berea,Madison County,15610,57100.0,57300.0,57500.0,...,136000,136900,137900,139300,140700,141500,141600,141700,142700,143500
15610,95851,89155,Mesquite,NV,Las Vegas-Henderson-Paradise,Clark County,15611,174900.0,174800.0,174700.0,...,346100,347800,351300,355100,358600,362500,367100,369400,370000,370800

In [14]:
zillow.set_index("RegionID", inplace=True)

zillow.head()

,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
RegionID,,,,,,,,,,,,,,,,,,,,,
61639,10025,New York,NY,New York-Newark-Jersey City,New York County,1,168300.0,168400.0,168400.0,168400.0,...,1115700,1108900,1097600,1086900,1080100,1072000,1065700,1051300,1027400,1009600
84654,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,160000.0,161000.0,161700.0,162000.0,...,350100,348500,347300,347400,348800,350800,352800,353200,352700,353000
61637,10023,New York,NY,New York-Newark-Jersey City,New York County,3,353100.0,353700.0,354200.0,354600.0,...,1501700,1487200,1461700,1439000,1412100,1391500,1381400,1373100,1364500,1361000
91982,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,210400.0,212200.0,212200.0,210700.0,...,334400,335800,337100,338400,338500,337000,336100,335900,335100,334300
84616,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,5,194400.0,196100.0,197300.0,197800.0,...,428200,428400,430000,430900,430000,430200,431700,432400,432200,432500

In [21]:
zillow = zillow.drop(zillow.columns[[0]],axis=1)

zillow.head()





#zillow.drop("City", axis=1, inplace=True)

,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,1996-10,1996-11,1996-12,1997-01,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
RegionID,,,,,,,,,,,,,,,,,,,,,
61639,168300.0,168400.0,168400.0,168400.0,168400.0,168600.0,169200.0,170000.0,171500.0,173300.0,...,1115700,1108900,1097600,1086900,1080100,1072000,1065700,1051300,1027400,1009600
84654,160000.0,161000.0,161700.0,162000.0,162000.0,161600.0,160800.0,159700.0,158500.0,157500.0,...,350100,348500,347300,347400,348800,350800,352800,353200,352700,353000
61637,353100.0,353700.0,354200.0,354600.0,354900.0,355400.0,356100.0,357100.0,358800.0,361100.0,...,1501700,1487200,1461700,1439000,1412100,1391500,1381400,1373100,1364500,1361000
91982,210400.0,212200.0,212200.0,210700.0,208300.0,205500.0,202500.0,199800.0,198300.0,197300.0,...,334400,335800,337100,338400,338500,337000,336100,335900,335100,334300
84616,194400.0,196100.0,197300.0,197800.0,197700.0,196900.0,195800.0,194200.0,193000.0,191900.0,...,428200,428400,430000,430900,430000,430200,431700,432400,432200,432500

In [23]:
zillow_new = pd.DataFrame(zillow)

zillow_new.head()

,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,1996-10,1996-11,1996-12,1997-01,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
RegionID,,,,,,,,,,,,,,,,,,,,,
61639,168300.0,168400.0,168400.0,168400.0,168400.0,168600.0,169200.0,170000.0,171500.0,173300.0,...,1115700,1108900,1097600,1086900,1080100,1072000,1065700,1051300,1027400,1009600
84654,160000.0,161000.0,161700.0,162000.0,162000.0,161600.0,160800.0,159700.0,158500.0,157500.0,...,350100,348500,347300,347400,348800,350800,352800,353200,352700,353000
61637,353100.0,353700.0,354200.0,354600.0,354900.0,355400.0,356100.0,357100.0,358800.0,361100.0,...,1501700,1487200,1461700,1439000,1412100,1391500,1381400,1373100,1364500,1361000
91982,210400.0,212200.0,212200.0,210700.0,208300.0,205500.0,202500.0,199800.0,198300.0,197300.0,...,334400,335800,337100,338400,338500,337000,336100,335900,335100,334300
84616,194400.0,196100.0,197300.0,197800.0,197700.0,196900.0,195800.0,194200.0,193000.0,191900.0,...,428200,428400,430000,430900,430000,430200,431700,432400,432200,432500

In [29]:
zillow_new.pct_change(axis='columns')

zillow_pct = pd.DataFrame(zillow_new.pct_change(axis='columns')
)

zillow_pct.head()

,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,1996-10,1996-11,1996-12,1997-01,...,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02
RegionID,,,,,,,,,,,,,,,,,,,,,
61639,NaN,0.000594,0.000000,0.000000,0.000000,0.001188,0.003559,0.004728,0.008824,0.010496,...,-0.003839,-0.006095,-0.010190,-0.009749,-0.006256,-0.007499,-0.005877,-0.013512,-0.022734,-0.017325
84654,NaN,0.006250,0.004348,0.001855,0.000000,-0.002469,-0.004950,-0.006841,-0.007514,-0.006309,...,-0.003699,-0.004570,-0.003443,0.000288,0.004030,0.005734,0.005701,0.001134,-0.001416,0.000851
61637,NaN,0.001699,0.001414,0.001129,0.000846,0.001409,0.001970,0.002808,0.004761,0.006410,...,0.003006,-0.009656,-0.017146,-0.015530,-0.018694,-0.014588,-0.007258,-0.006008,-0.006263,-0.002565
91982,NaN,0.008555,0.000000,-0.007069,-0.011391,-0.013442,-0.014599,-0.013333,-0.007508,-0.005043,...,0.005412,0.004187,0.003871,0.003856,0.000296,-0.004431,-0.002671,-0.000595,-0.002382,-0.002387
84616,NaN,0.008745,0.006119,0.002534,-0.000506,-0.004047,-0.005587,-0.008172,-0.006179,-0.005699,...,-0.001632,0.000467,0.003735,0.002093,-0.002089,0.000465,0.003487,0.001621,-0.000463,0.000694

In [ ]:
zillow_pct